let arr = [
  {
      id: Math.random(),
      name: 'Timur',
      info: {
          school: '235',
          faculity: 'SMM'
      },
  },
  {
      id: Math.random(),
      name: 'Imran',
      info: {
          school: 'ne izvestno',
          faculity: 'programming'
      },
  },
  {
      id: Math.random(),
      name: 'Aminjon',
      info: {
          school: '444',
          faculity: 'Dizayn'
      },
  },
  {
      id: Math.random(),
      name: 'Maxmud',
      info: {
          school: '777',
          faculity: '3dsmax'
      },
  },
  {
      id: Math.random(),
      name: 'Muxammad',
      info: {
          school: '5555',
          faculity: 'Backend'
      },
  },
  {
      id: Math.random(),
      name: 'Timur',
      info: {
          school: '235',
          faculity: 'SMM'
      },
  },
  {
      id: Math.random(),
      name: 'Imran',
      info: {
          school: 'ne izvestno',
          faculity: 'programming'
      },
  },
  {
      id: Math.random(),
      name: 'Aminjon',
      info: {
          school: '444',
          faculity: 'Dizayn'
      },
  },
  {
      id: Math.random(),
      name: 'Maxmud',
      info: {
          school: '777',
          faculity: '3dsmax'
      },
  },







  {
    id: Math.random(),
    name: 'Maxmud',
    info: {
        school: '777',
        faculity: '3dsmax'
    },
},
{
    id: Math.random(),
    name: 'Muxammad',
    info: {
        school: '5555',
        faculity: 'Backend'
    },
},
]

let categories = [
{
    course: 'SMM',
    count: 0
},
{
    course: 'programming',
    count: 0
},
{
    course: '3dsmax',
    count: 0
},
{
    course: 'Dizayn',
    count: 0
},
{       
    course: 'Backend',
    count: 0
},
]

for(let item of arr ){
    if(item.info.faculity === categories.course){
        arr.item.count++
      }
for(let ket of categories){
let key = ket.course.trim().toUppercase()
}
}



